version: '3.4'

services:

  matchmake.backend:
    image: ${DOCKER_REGISTRY-}matchmakebackend
    container_name: matchmake_backend
    depends_on:
      - postgres
      - rabbitmq
    build: MatchMake.Backend
    networks:
      - xo_internal_net
       
  postgres:
    image: postgres:alpine
    container_name: postgres
    ports:
      - 30000:5432
    restart: always
    volumes:
      - postgres_data:/var/opt/postgres
    environment:
      POSTGRES_USER: xo_admin
      POSTGRES_PASSWORD: xo_admin
    networks:
      - xo_internal_net

  postgres_adminer:
    image: adminer
    container_name: postgres_adminer
    restart: always
    ports:
      - 30001:8080
    networks:
      - xo_internal_net

  rabbitmq:
    image: rabbitmq:3.8-management-alpine
    container_name: rabbitmq
    restart: "unless-stopped"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - "./rabbitmq:/etc/match_back/"
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      - RABBITMQ_CONFIG_FILE=/etc/match_back/rabbitmq.conf
    networks:
      - xo_internal_net

volumes:
  postgres_data:
    external: true    
  rabbitmq_data:
    external: true

networks:
  xo_internal_net:
    name: xo_internal_net
    external: true